name: Publish App On GitHub Releaes

on:
  push:
    tags:
      - "v*"

jobs:
  job1:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

  job2:
    name: Build
    needs: job1
    runs-on: windows-latest

    env:
      AppName: KMSGuildExtractor
      WpfProjectDir: src\KMSGuildExtractor

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.5.0
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Publish app
        run: |
          dotnet publish -c release --no-restore .\${{ env.WpfProjectDir }} -p:PublishDir=.\.publish
          Compress-Archive .\${{ env.WpfProjectDir }}\.publish\* ${{ env.AppName }}.zip

      - name: Update release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.job1.outputs.upload_url }}
          asset_path: ${{ env.AppName }}.zip
          asset_name: ${{ env.AppName }}.zip
          asset_content_type: application/zip
