name: Publish App On GitHub Releaes

on:
    push:
        tags:
            - "v*"

jobs:
    job1:
        name: Create Release
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}

        steps:
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: ${{ github.ref }}
                  draft: true
                  prerelease: false

    job2:
        name: Build
        needs: job1
        runs-on: windows-latest
        strategy:
            matrix:
                targetPlatform: [win-x86, win-x64]

        env:
            AppName: KMSGuildExtractor
            WpfProjectDir: src\KMSGuildExtractor

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                  fetch-depth: 0

            - name: Setup .NET Core SDK
              uses: actions/setup-dotnet@v1.5.0
              with:
                  # SDK version to use. Examples: 2.2.104, 3.1, 3.1.x
                  dotnet-version: 3.1.x

            - name: Install dependencies
              run: dotnet restore

            - name: Publish app
              run: dotnet publish .\$env:WpfProjectDir -c Release -r ${{ matrix.targetPlatform }} -p:PublishSingleFile=true -p:PublishTrimmed=true

            - name: Update release asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1.0.2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.job1.outputs.upload_url }}
                  asset_path: .\${{ env.WpfProjectDir }}\bin\Release\netcoreapp3.1\${{ matrix.targetPlatform }}\publish\${{ env.AppName }}.exe
                  asset_name: ${{ env.AppName }}_${{ matrix.targetPlatform }}.exe
                  asset_content_type: application/octet-stream
